FROM node:20-alpine AS builder
WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/ ./apps/
COPY tsconfig.base.json ./
COPY tsconfig.base.json ./tsconfig.json

RUN cp packages/database/prisma/schema.postgres.prisma packages/database/prisma/schema.prisma

RUN npm install

RUN npx prisma generate --schema=packages/database/prisma/schema.prisma

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV NEXT_PUBLIC_APP_URL=https://novaqa.thebuildflow.site
ENV NEXT_PUBLIC_API_URL=/api/v1
RUN npm run build --workspace=@novaqa/web

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs &&     adduser --system --uid 1001 nextjs

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/apps ./apps
COPY --from=builder /app/tsconfig*.json ./

RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=15s --timeout=5s --start-period=10s --retries=3   CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

CMD ["npm", "run", "start", "--workspace=@novaqa/web"]
